name: Mascot
favicon: null
layout_spectrum: 0.45282881218008697
typography_spectrum: 0.5798427958507091
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.43265959178097546
  lightness: 0.9331883846316487
  saturation: 0.15097151696681976
  rhythmicContrast: 0.9433979047462344
purpose: []
