name: Mascot
favicon: null
layout_spectrum: 0.45282881218008697
typography_spectrum: 0.28156
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#fd3850'
    - '#060606'
    - '#429090'
    - '#9ac5c3'
  brandStrength: 0.75
  lightness: 0.9331883846316487
  saturation: 0.15097151696681976
  rhythmicContrast: 0.9433979047462344
purpose: []
